App2/urls.py
from django.urls import URLPattern, path
from App2.views import *
app_name='App2'

urlpatterns=[
    path('Sthird/',Sthird,name='Sthird'),
]

Pro2/urls.py
from django.contrib import admin
from django.urls import path,include
from App1.views import *
import App2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('First/',First,name='First'),
    path('Second/',Second,name='Second'),
    path('App2/',include('App2.urls'))

]

App1/models.py
from django.db import models

# Create your models here.

App2/models.py
from django.db import models

# Create your models here.

App1/views.py
from django.shortcuts import render

# Create your views here.

def First(request):
    return render(request,'First.html')

def Second(request):
    return render(request,'Second.html')

App2/views.py
from django.shortcuts import render

# Create your views here.

def Sthird(request):
    return render(request,'Sthird.html')

templates/First.html
<html>
<head>
    <title>First Html Page</title>
</head>
<body>
    <center>
        <h1> Welcome To </h1>
        <h1> First Html Page</h1>
        <a href="{% url 'Second' %}"> Go to Second html page </a>
        <br>
        <a href="{% url 'App2:Sthird' %}"> Go to Sthird html page </a>
    </center>
    
</body>
</html>

templates/Second.html
<html>
<head>
    <title>Second Html Page</title>
</head>
<body>
    <center>
        <h1> Welcome To </h1>
        <h1> Second Html Page </h1>
        <a href="{% url 'First' %}"> Go to First html page </a>
        <br>
        <a href="{% url 'App2:Sthird' %}"> Go to Sthird html page </a>
    </center>
    
</body>
</html>

templates/Sthird.html
<html>
<head>
    <title>Second Html Page</title>
</head>
<body>
    <center>
        <h1> Welcome To </h1>
        <h1> Sthird Html Page </h1>
        <a href="{% url 'First' %}"> Go to First html page </a>
        <br>
        <a href="{% url 'Second' %}"> Go to Second html page </a>
    </center>
    
</body>
</html>